{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc.acp",
    "module": "ACP-Gradle",
    "version": "0.1.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ACP-Gradle-0.1.0-beta.jar",
          "url": "ACP-Gradle-0.1.0-beta.jar",
          "size": 14851,
          "sha512": "3a2b54da328e9e26fb665425f77bc4750d3663abd7f1f5dbe582f4d55a6bfc17708f9d1b0b6bc3f4db931d5ed905821cfe74c626619982fb97539632b4e0d8bd",
          "sha256": "0c4e814f651d3686394eeac71efd631b5cabc1a45314cd73a642466dc3ccbfbe",
          "sha1": "9b65f4c575426411281a5eca0ea1e8f16fc5fcac",
          "md5": "cc425182b75a6134b1b4c8c816c5d62b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ACP-Gradle-0.1.0-beta.jar",
          "url": "ACP-Gradle-0.1.0-beta.jar",
          "size": 14851,
          "sha512": "3a2b54da328e9e26fb665425f77bc4750d3663abd7f1f5dbe582f4d55a6bfc17708f9d1b0b6bc3f4db931d5ed905821cfe74c626619982fb97539632b4e0d8bd",
          "sha256": "0c4e814f651d3686394eeac71efd631b5cabc1a45314cd73a642466dc3ccbfbe",
          "sha1": "9b65f4c575426411281a5eca0ea1e8f16fc5fcac",
          "md5": "cc425182b75a6134b1b4c8c816c5d62b"
        }
      ]
    }
  ]
}
