{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc.acp",
    "module": "ACP-Gradle",
    "version": "0.1.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ACP-Gradle-0.1.0-beta.jar",
          "url": "ACP-Gradle-0.1.0-beta.jar",
          "size": 14519,
          "sha512": "1f26ed2b458d729a83765e7fb06cde9789b5a650ad338be403aab6236cbd4c21070a8cea2e50ae7710a7cedf5f39d5035b5f051e53b7be55b1c249e5a81a00af",
          "sha256": "50947f4dd825073f87e72e0377f55319e83d864516440b2f2e067e90dc74649e",
          "sha1": "01c0d0808f96365224acf155c8d6dde6a900d07b",
          "md5": "0a51d6370a5f34ec7c5c16e470da2718"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ACP-Gradle-0.1.0-beta.jar",
          "url": "ACP-Gradle-0.1.0-beta.jar",
          "size": 14519,
          "sha512": "1f26ed2b458d729a83765e7fb06cde9789b5a650ad338be403aab6236cbd4c21070a8cea2e50ae7710a7cedf5f39d5035b5f051e53b7be55b1c249e5a81a00af",
          "sha256": "50947f4dd825073f87e72e0377f55319e83d864516440b2f2e067e90dc74649e",
          "sha1": "01c0d0808f96365224acf155c8d6dde6a900d07b",
          "md5": "0a51d6370a5f34ec7c5c16e470da2718"
        }
      ]
    }
  ]
}
