{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc.acp",
    "module": "acp-gradle",
    "version": "0.2.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "acp-gradle-0.2.0-beta.jar",
          "url": "acp-gradle-0.2.0-beta.jar",
          "size": 24091,
          "sha512": "00c2f9bc3a7cea5e6e97dbf94c0a7b5f09e09b05b7da57d58678acc68b101ff4424a4cdd71a3369b291bf3bdd201ab1481926b014bb05ba1112776abd251d0ea",
          "sha256": "102efbf68248cedfa5798bb1bbb9586300e2fed93424bd603188fad956214a74",
          "sha1": "e3420f03087696bfdb836f4b0eda91a89358649f",
          "md5": "a1851eabf28e65489d75d3fe7d580aff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "acp-gradle-0.2.0-beta.jar",
          "url": "acp-gradle-0.2.0-beta.jar",
          "size": 24091,
          "sha512": "00c2f9bc3a7cea5e6e97dbf94c0a7b5f09e09b05b7da57d58678acc68b101ff4424a4cdd71a3369b291bf3bdd201ab1481926b014bb05ba1112776abd251d0ea",
          "sha256": "102efbf68248cedfa5798bb1bbb9586300e2fed93424bd603188fad956214a74",
          "sha1": "e3420f03087696bfdb836f4b0eda91a89358649f",
          "md5": "a1851eabf28e65489d75d3fe7d580aff"
        }
      ]
    }
  ]
}
