{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "forgeflower",
    "version": "1.0-am",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "forgeflower-1.0-am.jar",
          "url": "forgeflower-1.0-am.jar",
          "size": 714861,
          "sha512": "1d9db1354b84934142a6750b111af977e1736553f76d448e5852957a5f527d89a88a0c8193a95b664734bad62f8e9a14e6b91dc0abb7c1143b4c545d886ccb6e",
          "sha256": "3d1d5b442e6bfc1a78ee21985ba7439296364ce7d295c81c4c2b954e60811456",
          "sha1": "b36315605326a549a9cdf17f69d1d95512332462",
          "md5": "1461c6e533ca657a2a65106f1925392f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "forgeflower-1.0-am.jar",
          "url": "forgeflower-1.0-am.jar",
          "size": 714861,
          "sha512": "1d9db1354b84934142a6750b111af977e1736553f76d448e5852957a5f527d89a88a0c8193a95b664734bad62f8e9a14e6b91dc0abb7c1143b4c545d886ccb6e",
          "sha256": "3d1d5b442e6bfc1a78ee21985ba7439296364ce7d295c81c4c2b954e60811456",
          "sha1": "b36315605326a549a9cdf17f69d1d95512332462",
          "md5": "1461c6e533ca657a2a65106f1925392f"
        }
      ]
    }
  ]
}
