{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc.acp",
    "module": "acp-gradle",
    "version": "0.1.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "acp-gradle-0.1.1-beta.jar",
          "url": "acp-gradle-0.1.1-beta.jar",
          "size": 15062,
          "sha512": "5c2b5f884939728c313b3b6d6afefa7e47b72c85dec416ae6bd47bea7ad925f48cd07840935e46352ce09d36975f66d096c2a88d4c4c0c0c7e8cd5ba9d9c64a2",
          "sha256": "55ce4d1a1f9a3defb5bd49d51ba03c9c24750dbc56fc4e978baf7778ccc65929",
          "sha1": "9289dfb38c79e017537fc1716cf04b41a06269d8",
          "md5": "8549d8bd1eddb4b4c517517b06b76365"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "acp-gradle-0.1.1-beta.jar",
          "url": "acp-gradle-0.1.1-beta.jar",
          "size": 15062,
          "sha512": "5c2b5f884939728c313b3b6d6afefa7e47b72c85dec416ae6bd47bea7ad925f48cd07840935e46352ce09d36975f66d096c2a88d4c4c0c0c7e8cd5ba9d9c64a2",
          "sha256": "55ce4d1a1f9a3defb5bd49d51ba03c9c24750dbc56fc4e978baf7778ccc65929",
          "sha1": "9289dfb38c79e017537fc1716cf04b41a06269d8",
          "md5": "8549d8bd1eddb4b4c517517b06b76365"
        }
      ]
    }
  ]
}
