{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.moist-mason",
    "module": "license-importer",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "license-importer-1.0.jar",
          "url": "license-importer-1.0.jar",
          "size": 3065,
          "sha512": "79caf7a2020357376b675acf2c58f0232a2ad4beb870eec6b1c17d59a07551c93016ba1e543689f58369d379fe6afe48e97f950e2541a7c2af5ea74913315361",
          "sha256": "7b082071c0a34e32e419d477fbeaacc5b04390a2bc397448df2b1d8409b06d68",
          "sha1": "47f4ae5a0d4dc9b002a9b77ae92ed957bfff4d4a",
          "md5": "eb9a3029e15aa2d4244ddd26b571f725"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "license-importer-1.0.jar",
          "url": "license-importer-1.0.jar",
          "size": 3065,
          "sha512": "79caf7a2020357376b675acf2c58f0232a2ad4beb870eec6b1c17d59a07551c93016ba1e543689f58369d379fe6afe48e97f950e2541a7c2af5ea74913315361",
          "sha256": "7b082071c0a34e32e419d477fbeaacc5b04390a2bc397448df2b1d8409b06d68",
          "sha1": "47f4ae5a0d4dc9b002a9b77ae92ed957bfff4d4a",
          "md5": "eb9a3029e15aa2d4244ddd26b571f725"
        }
      ]
    }
  ]
}
