{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.moist-mason",
    "module": "license-importer",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "license-importer-1.0.jar",
          "url": "license-importer-1.0.jar",
          "size": 2707,
          "sha512": "adbbb552321089c3a295d4c50cc22358643fd61fdfebd58da238236f8965e6881a870fb1a16214b9f8d9424dad160ac0f4ccf952d107d2f72cc6f5aa5ee045e8",
          "sha256": "a59ade3921e4c4dde6c27e1a0202389ce6020976c9e03dc8a58eb13defbb5f67",
          "sha1": "2b6bbc7a16f50e3c61916de90adc687747d1758d",
          "md5": "c9eb2a0f310eae8154b1e19db8fb68b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "license-importer-1.0.jar",
          "url": "license-importer-1.0.jar",
          "size": 2707,
          "sha512": "adbbb552321089c3a295d4c50cc22358643fd61fdfebd58da238236f8965e6881a870fb1a16214b9f8d9424dad160ac0f4ccf952d107d2f72cc6f5aa5ee045e8",
          "sha256": "a59ade3921e4c4dde6c27e1a0202389ce6020976c9e03dc8a58eb13defbb5f67",
          "sha1": "2b6bbc7a16f50e3c61916de90adc687747d1758d",
          "md5": "c9eb2a0f310eae8154b1e19db8fb68b8"
        }
      ]
    }
  ]
}
