{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.moist-mason",
    "module": "license-importer",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "license-importer-1.0.jar",
          "url": "license-importer-1.0.jar",
          "size": 3096,
          "sha512": "336178c82fc946845b618932db60c304fca53f6edf05a2f0d15b610bbf23357195f613cf6a47f0246ec72aa896fd6f19f5aa358c8eaa881b0f7af759da3062c6",
          "sha256": "d01d1996de597a3dd68daf4e3ee9cf742b3acabf87a4292769caa6ab12f5e489",
          "sha1": "f15ea4b8ffc610ced2a94be40c6f34b07a5af5fe",
          "md5": "c4a2d4d71a4ba4a1d6076b78b3b3878d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "license-importer-1.0.jar",
          "url": "license-importer-1.0.jar",
          "size": 3096,
          "sha512": "336178c82fc946845b618932db60c304fca53f6edf05a2f0d15b610bbf23357195f613cf6a47f0246ec72aa896fd6f19f5aa358c8eaa881b0f7af759da3062c6",
          "sha256": "d01d1996de597a3dd68daf4e3ee9cf742b3acabf87a4292769caa6ab12f5e489",
          "sha1": "f15ea4b8ffc610ced2a94be40c6f34b07a5af5fe",
          "md5": "c4a2d4d71a4ba4a1d6076b78b3b3878d"
        }
      ]
    }
  ]
}
