{
  "formatVersion": "1.1",
  "component": {
    "group": "com.entropy.rcp",
    "module": "RCP-Gradle",
    "version": "0.1.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RCP-Gradle-0.1.0-beta.jar",
          "url": "RCP-Gradle-0.1.0-beta.jar",
          "size": 14449,
          "sha512": "2d7a8a5fcce2655cfefba8e2712d2d57e4373c268677feef223cf63c2f7725793c14895ade62a9e6b4cdfc6d92870fe711227c5a75924e1912e218aa34a7106b",
          "sha256": "7ebe2d0d0dd54a18ba4f454513b1b10cd984d8b14a12e0580c2ad83749bb9281",
          "sha1": "df6e3933f1ba4f7e0373f396a8cccfea0c452b75",
          "md5": "16b8ef44698c0ceffa72d96c18c03847"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "RCP-Gradle-0.1.0-beta.jar",
          "url": "RCP-Gradle-0.1.0-beta.jar",
          "size": 14449,
          "sha512": "2d7a8a5fcce2655cfefba8e2712d2d57e4373c268677feef223cf63c2f7725793c14895ade62a9e6b4cdfc6d92870fe711227c5a75924e1912e218aa34a7106b",
          "sha256": "7ebe2d0d0dd54a18ba4f454513b1b10cd984d8b14a12e0580c2ad83749bb9281",
          "sha1": "df6e3933f1ba4f7e0373f396a8cccfea0c452b75",
          "md5": "16b8ef44698c0ceffa72d96c18c03847"
        }
      ]
    }
  ]
}
