{
  "formatVersion": "1.1",
  "component": {
    "group": "com.paulscode",
    "module": "codecjorbis-impl",
    "version": "20221222",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codecjorbis-impl-20221222.jar",
          "url": "codecjorbis-impl-20221222.jar",
          "size": 108773,
          "sha512": "f6a162286f9888350d63bb02791eacd89f6c60b9a4037f510f50b6bbdba180b17bc32e03ca32d9ea379bc0e4054923933a267e8f995bd31e8122e22619dc2ff3",
          "sha256": "5b1326b8ee8621058129de259eed97a2fc525f81ae509833c45b236955ed5c65",
          "sha1": "0f098969a26c877a9de19acfcac0d63322ae32f0",
          "md5": "49b6e5104950e15a5eef1b590ec7129b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.paulscode",
          "module": "soundsystem",
          "version": {
            "requires": "20120107"
          }
        }
      ],
      "files": [
        {
          "name": "codecjorbis-impl-20221222.jar",
          "url": "codecjorbis-impl-20221222.jar",
          "size": 108773,
          "sha512": "f6a162286f9888350d63bb02791eacd89f6c60b9a4037f510f50b6bbdba180b17bc32e03ca32d9ea379bc0e4054923933a267e8f995bd31e8122e22619dc2ff3",
          "sha256": "5b1326b8ee8621058129de259eed97a2fc525f81ae509833c45b236955ed5c65",
          "sha1": "0f098969a26c877a9de19acfcac0d63322ae32f0",
          "md5": "49b6e5104950e15a5eef1b590ec7129b"
        }
      ]
    }
  ]
}
