{
  "formatVersion": "1.1",
  "component": {
    "group": "com.paulscode",
    "module": "codecjorbis-impl",
    "version": "20221222",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codecjorbis-impl-20221222.jar",
          "url": "codecjorbis-impl-20221222.jar",
          "size": 108774,
          "sha512": "e757975fb3bce301f4845c797fd748cf21638909753c80f8372eda87fc868907318986e89cb5e50b0c7aeef3974c48d5344ac737ba394cac0e20b8c509be0fab",
          "sha256": "b3dd43a037bac7ed99ae239c528663e1aee31e9ecf9f74afa2c3e1628ac09f46",
          "sha1": "c53ee86b12bb85ea5e88748c7cca27b2d0830b3b",
          "md5": "a6a433db1696a558c7c752bd5d507f6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.paulscode",
          "module": "soundsystem",
          "version": {
            "requires": "20120107"
          }
        }
      ],
      "files": [
        {
          "name": "codecjorbis-impl-20221222.jar",
          "url": "codecjorbis-impl-20221222.jar",
          "size": 108774,
          "sha512": "e757975fb3bce301f4845c797fd748cf21638909753c80f8372eda87fc868907318986e89cb5e50b0c7aeef3974c48d5344ac737ba394cac0e20b8c509be0fab",
          "sha256": "b3dd43a037bac7ed99ae239c528663e1aee31e9ecf9f74afa2c3e1628ac09f46",
          "sha1": "c53ee86b12bb85ea5e88748c7cca27b2d0830b3b",
          "md5": "a6a433db1696a558c7c752bd5d507f6f"
        }
      ]
    }
  ]
}
