{
  "formatVersion": "1.1",
  "component": {
    "group": "com.paulscode",
    "module": "codecjorbis-impl",
    "version": "20221222",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codecjorbis-impl-20221222.jar",
          "url": "codecjorbis-impl-20221222.jar",
          "size": 108774,
          "sha512": "cb297515960488e8ec0a66806d3978ed971a87ead563aa72c92de130cc9b9aeb2bb4169f10220884f6375bdbe48d0a77bf7e83a465e412de624ac11e6a722dda",
          "sha256": "8312103c0e8f9598187efbf2e2ce4fc19d0628a2910be829d176ed96ac786ded",
          "sha1": "dd5927cb4537499fa5437ede2c690e9f24b4c68b",
          "md5": "c9843971e5888990610a1534d447c2cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.paulscode",
          "module": "soundsystem",
          "version": {
            "requires": "20120107"
          }
        }
      ],
      "files": [
        {
          "name": "codecjorbis-impl-20221222.jar",
          "url": "codecjorbis-impl-20221222.jar",
          "size": 108774,
          "sha512": "cb297515960488e8ec0a66806d3978ed971a87ead563aa72c92de130cc9b9aeb2bb4169f10220884f6375bdbe48d0a77bf7e83a465e412de624ac11e6a722dda",
          "sha256": "8312103c0e8f9598187efbf2e2ce4fc19d0628a2910be829d176ed96ac786ded",
          "sha1": "dd5927cb4537499fa5437ede2c690e9f24b4c68b",
          "md5": "c9843971e5888990610a1534d447c2cb"
        }
      ]
    }
  ]
}
