{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc.acp",
    "module": "acp-gradle",
    "version": "0.2.0-beta-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "acp-gradle-0.2.0-beta-dev.jar",
          "url": "acp-gradle-0.2.0-beta-dev.jar",
          "size": 42061,
          "sha512": "5f424e37e4b306bfc9840cf5c4c26a18488742e532d69d30c27cba61186a7ceefffc757b2bdb4b76de42c01b3906dafc0afb0939cd9fbbfe563a01290165ec13",
          "sha256": "1df8004dd2ffe2cb91ced73bc7479b06ed7d3bfd5368a0d8a10277fb211ca3d5",
          "sha1": "b92af835c925da29a07f6078352655881db15ae3",
          "md5": "35bc7243c59fc41d4c4a9e5f0da1222c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.13"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        }
      ],
      "files": [
        {
          "name": "acp-gradle-0.2.0-beta-dev.jar",
          "url": "acp-gradle-0.2.0-beta-dev.jar",
          "size": 42061,
          "sha512": "5f424e37e4b306bfc9840cf5c4c26a18488742e532d69d30c27cba61186a7ceefffc757b2bdb4b76de42c01b3906dafc0afb0939cd9fbbfe563a01290165ec13",
          "sha256": "1df8004dd2ffe2cb91ced73bc7479b06ed7d3bfd5368a0d8a10277fb211ca3d5",
          "sha1": "b92af835c925da29a07f6078352655881db15ae3",
          "md5": "35bc7243c59fc41d4c4a9e5f0da1222c"
        }
      ]
    }
  ]
}
