{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc.acp",
    "module": "acp-gradle",
    "version": "0.2.0-beta-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "acp-gradle-0.2.0-beta-dev.jar",
          "url": "acp-gradle-0.2.0-beta-dev.jar",
          "size": 42061,
          "sha512": "1caa1d9f0184eb7f3660081548862d6b7a4156245346928788fb14e90e86a67121a187cf2be10142267062fedde689255153ba01afed9fd84d10a8bc2bcb44b4",
          "sha256": "d5f8cc79aa391ae306398245893ec5ff309f93e31a40c3579b21ebfb1649a2e6",
          "sha1": "f46cb7bc75353048e42f4b149c2031cdf8bb3065",
          "md5": "e3ecebd8ad9dfed39c66873f38d18291"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.13"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        }
      ],
      "files": [
        {
          "name": "acp-gradle-0.2.0-beta-dev.jar",
          "url": "acp-gradle-0.2.0-beta-dev.jar",
          "size": 42061,
          "sha512": "1caa1d9f0184eb7f3660081548862d6b7a4156245346928788fb14e90e86a67121a187cf2be10142267062fedde689255153ba01afed9fd84d10a8bc2bcb44b4",
          "sha256": "d5f8cc79aa391ae306398245893ec5ff309f93e31a40c3579b21ebfb1649a2e6",
          "sha1": "f46cb7bc75353048e42f4b149c2031cdf8bb3065",
          "md5": "e3ecebd8ad9dfed39c66873f38d18291"
        }
      ]
    }
  ]
}
