{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc.acp",
    "module": "acp-gradle",
    "version": "0.2.0-beta-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "acp-gradle-0.2.0-beta-dev.jar",
          "url": "acp-gradle-0.2.0-beta-dev.jar",
          "size": 42666,
          "sha512": "41cca9bb97f20fcc4ad478ce24051971fdb71fc34e6cecf39a7287f8b386fab7d7b25704ee6dfe407b843778b5c763b6fe501927641b3dbf470944746db62699",
          "sha256": "bb220234752d8fba6ea97296cd6be00b2bf848a84f7a4e1782f912ecc1c74578",
          "sha1": "d8edf56bdefa675b76e4f0df630bd7b7febd0617",
          "md5": "72e76983965f597e57596fb797bf3064"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.13"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        }
      ],
      "files": [
        {
          "name": "acp-gradle-0.2.0-beta-dev.jar",
          "url": "acp-gradle-0.2.0-beta-dev.jar",
          "size": 42666,
          "sha512": "41cca9bb97f20fcc4ad478ce24051971fdb71fc34e6cecf39a7287f8b386fab7d7b25704ee6dfe407b843778b5c763b6fe501927641b3dbf470944746db62699",
          "sha256": "bb220234752d8fba6ea97296cd6be00b2bf848a84f7a4e1782f912ecc1c74578",
          "sha1": "d8edf56bdefa675b76e4f0df630bd7b7febd0617",
          "md5": "72e76983965f597e57596fb797bf3064"
        }
      ]
    }
  ]
}
