{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ancientmc",
    "module": "fernflower",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fernflower-1.0.jar",
          "url": "fernflower-1.0.jar",
          "size": 711755,
          "sha512": "e9bf60323dc3712490271848c625f2f3b6839121055e9a5d7d8643729c2a5eb0301eeafd765a782227119b09c26af278276f71d5174db01494e817b98fd47a03",
          "sha256": "734de27900ce96a15771a06567c4adc04df827ba5eb1154db5ee6a9f067cbd2b",
          "sha1": "8bf26fcf6e4e330e891667451580691ab8c15944",
          "md5": "3f59766a071e12d72956408fecf0605d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fernflower-1.0.jar",
          "url": "fernflower-1.0.jar",
          "size": 711755,
          "sha512": "e9bf60323dc3712490271848c625f2f3b6839121055e9a5d7d8643729c2a5eb0301eeafd765a782227119b09c26af278276f71d5174db01494e817b98fd47a03",
          "sha256": "734de27900ce96a15771a06567c4adc04df827ba5eb1154db5ee6a9f067cbd2b",
          "sha1": "8bf26fcf6e4e330e891667451580691ab8c15944",
          "md5": "3f59766a071e12d72956408fecf0605d"
        }
      ]
    }
  ]
}
